### PR TITLE
Add flatpak setup script

### PR DESCRIPTION
**Pull request by rany2**
This script automatically builds and configures Spotify flatpak to use spotify-adblock-linux. All you have to do is run the script and it would be done.

You need to install Spotify flatpak first, though. (`flatpak install flathub com.spotify.Client`)

### CODE REVIEW

**Comment by rany2** [comment]
just tested it, it doesn't actually work. Does anyone know why?

```
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
dlsym (cef_urlrequest_create): /home/user/code/github/abba23/spotify-adblock-linux/spotify-adblock.so: undefined symbol: cef_urlrequest_create
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
```

**Comment by rany2** [comment]
update: the issue is that /app/bin/spotify sets its own LD_PRELOAD which is something we don't want... it works after doing: `LD_PRELOAD=/path/to/spotify-adblock.so /app/extra/bin/spotify`

**Comment by rany2** [comment]
This works now!

**Comment by rany2** [comment]
I added another script that just uses the shared library from GH Releases because I don't want to install the Sdk on my machine. It works just like `./flatpak-build` except it doesn't build it from scratch.

**Comment by Dyras** [comment]
Just wanna say thanks for doing the world into a better place <3

**Comment by rany2** [comment]
Did it work for you?

**Comment by Dyras** [comment]
Don't have access to a Linux install atm. Will try later!

**Comment by rany2** [comment]
Make sure to use the latest commit because I've changed the way the .desktop is made

**Comment by abba23** [comment]
I don't think adding a bunch of scripts that download and install things is a good way to go about this. Since I don't use Flatpak myself, this also isn't something I would be able to debug or maintain. I'd much prefer some simple and minimal instructions in the readme.

**Comment by rany2** [comment]
Done: https://github.com/rany2/spotify-adblock-linux/blob/master2/README.md

**Pull request closed without merging**
