### PR TITLE
use yaml config file

### PR DESCRIPTION
**Pull request by milahu**
solve issue #119

the new version will try to load

1. workdir config: `spotify-adblock-linux.yaml`
2. user config: `~/.config/spotify-adblock-linux/config.yaml`
3. system config: `/etc/spotify-adblock-linux/config.yaml`

if no config file is found, write default values (from `blacklist.h` and `whitelist.h`) to user config file

add script `generate-config-yaml.sh` to generate `config.yaml`

allow early debug by setting env-var `DEBUG=1`

use `libcyaml` to parse yaml to c struct
default values are set manually, since libcyaml is yet lacking [that feature](https://github.com/tlsa/libcyaml/issues/96)

known issue: low-level errors like
`symbol lookup error: /lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free`
or
`/bin/bash: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory`
are only printed in a debugger
but these should be visible in a regular program call
(edit: TODO verify calling wrapper vs binary executable (NixOS likes to wrap binaries))

wrapping `main` in `LD_PRELOAD` and `int __libc_start_main` is a rare scenario
but such low-level errors are even more rare, why i havent found a solution yet

i also added `-lcef` to Makefile LDLIBS to fix "undefined symbol: cef_string_userfree_utf16_free"
probably this is only an issue on my system (NixOS)
and i have to fix my LDFLAGS ... hope to fix this soon

fwiw, here is my [spotify-adblock-linux/default.nix](https://github.com/milahu/nur-packages/blob/master/pkgs/spotify-adblock-linux/default.nix) build file

edit: `fatal error: glib.h: No such file or directory`
-> probably the easiest fix is to add `pkg-config --cflags glib-2.0` to `CFLAGS`

edit: oof debian! [these](https://packages.debian.org/testing/source/libcyaml) are only in debian bullseye

> E: Unable to locate package libcyaml1
> E: Unable to locate package libcyaml-dev

could be added: CLI
`--help` to show CLI synopsis
`--adblock-print-config` to print default config to stdout
`--adblock-write-config` to write default config to ~/.config/spotify-adblock-linux/config.yaml
`--adblock-config <path>` to use config file in custom path

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
Nice work with the user-level config ability.

**Comment by abba23** [comment]
I've said this before in the issue, but you're adding hundreds of new lines of code (many times more than the current size of the code base) and new dependencies here, generally making building and maintaining the project a lot more difficult. All of it apparently, just to save a bit of time when packaging on NixOS. I like the idea of having a configurable white- and blacklist, but this hardly seems proportionate.

**Comment by milahu** [comment]
its a tradeoff ...

> I like the idea of having a configurable white- and blacklist, but this hardly seems proportionate.

```
300 000 KB spotify/
    150 KB libyaml.so
     50 KB libcyaml.so
     20 KB spotify-adblock.so
```

`glib` is also used by spotify, so thats zero cost

code size could be reduced by using a custom config parser
for example `ini` file format with arrays

```
[config]
debug = true

[blacklist]
https://spclient.wg.spotify.com/ads/* # ads
https://spclient.wg.spotify.com/ad-logic/* # ads

[whitelist]
localhost # local proxies
audio-sp-*.pscdn.co # audio
```

... but THAT seems out-of-proportion, just to save some kilobytes
(assuming that libyaml.so and libcyaml.so are not installed)

> [...] generally making building and maintaining the project a lot more difficult.

now youre exaggerating ; )

> All of it apparently, just to save a bit of time when packaging on NixOS.

this would allow all users to quickly update the config
including those users who just dont want to recompile `spotify-adblock.so`

**Comment by milahu** [comment]
closing in favor of https://github.com/abba23/spotify-adblock

**Pull request closed without merging**
