### PR TITLE
Add podcast whitelist and .gitignore

### PR DESCRIPTION
**Pull request by zhaqenl**

### CODE REVIEW

**Comment by abba23** [comment]
Thanks for the pull request!
Can you provide any examples for podcasts that don't work without allowing `*.simplecast.com`? I just tried playing some random ones and they all seemed to work fine.

Please also make these minor changes:
* Move the new whitelist entry to keep with the alphabetical order (ignoring the `*.`)
* Add a newline at the end of the `.gitignore` file

**Comment by zhaqenl** [comment]
The `Developer Tea` podcast doesn’t work for me.

Okay, sure, didn’t notice the first one!

**Comment by abba23** [comment]
Thanks for the changes.

>The `Developer Tea` podcast doesn’t work for me.

[This one](https://open.spotify.com/show/02fM1JHpt9HmHGp482K71b)? Works fine for me with the current whitelist. Which domains exactly does it show in the terminal log for you when you try to play it?

**Comment by zhaqenl** [comment]
Yes, that’s the one. That’s weird:

spotblock

**Comment by abba23** [comment]
Okay, I definitely don't have those. Maybe it depends on your location.

If it's only those two domains, then I'd rather have them separate and not use a wildcard though. That would preempt accidentally allowing connections to new subdomains like `ads.simplecast.com`.

**Comment by zhaqenl** [comment]
Okay, that’s a good point. Should I whitelist those two subdomains explicitly, then?

**Pull request merged**
