### PR TITLE
Whitelist genius.com and musixmatch.com (Fixes #66)

### LINKED ISSUE #66: Support for genius-spicetify
Currently using the adblock the spicetify module [genius-spicetify](https://github.com/khanhas/genius-spicetify) can't load the lyrics

### PR DESCRIPTION
**Pull request by alsoGAMER**

### CODE REVIEW

**Comment by abba23** [comment]
Are you sure `musixmatch.com` is needed at all? I did a bit of testing and for me just adding `genius.com` to the whitelist was enough to make it work. Either way, adding both `apic-desktop.musixmatch.com` and `*.musixmatch.com` is redundant.

It would also be a good idea I think to mention `genius-spicetify` in the comment(s) (i.e. `// lyrics (genius-spicetify)`) to make it clear that this isn't needed by Spotify itself, but an external modification.

**Comment by alsoGAMER** [comment]
> Are you sure `musixmatch.com` is needed at all? I did a bit of testing and for me just adding `genius.com` to the whitelist was enough to make it work.
Yeah, cause the mod also integrates with musixmatch.com. More about this [here](https://github.com/khanhas/genius-spicetify#musicxmatch)

> Either way, adding both `apic-desktop.musixmatch.com` and `*.musixmatch.com` is redundant.
I inserted a wildcard to avoid any problems with musixmatch API requests, as they could be made to a non-whitelisted endpoint.
Anyway, if it's possible to whitelist something like "api*-desktop.musixmatch.com", I'll change to that ASAP.

> It would also be a good idea I think to mention `genius-spicetify` in the comment(s) (i.e. `// lyrics (genius-spicetify)`) to make it clear that this isn't needed by Spotify itself, but an external modification.
Done.

**Comment by mariansam** [comment]
@abba23, would you please merge this? It works flawlessly. @noaccOS and I are still waiting for this.

**Comment by abba23** [comment]
>Yeah, cause the mod also integrates with musixmatch.com.

Okay, that seems reasonable then.

>Anyway, if it's possible to whitelist something like "api*-desktop.musixmatch.com", I'll change to that ASAP.

Yes, that should work. It can't hurt to test it and make sure that it still works correctly though.

Can you please move any new entries so that the list stays sorted alphabetically by top level domain, then second level domain etc. (e.g. a.com, b.com, a.net, a.a.net, b.a.net, b.net)? Also, just a small nitpick, but please add a space after the `//` like all the other comments have.

**Comment by abba23** [comment]
The entries still aren't in the correct order. `genius.com` would go after `platform-lookaside.fbsbx.com` and `api*-desktop.musixmatch.com` belongs after `traffic.libsyn.com`

**Comment by alsoGAMER** [comment]
> The entries still aren't in the correct order. `genius.com` would go after `platform-lookaside.fbsbx.com` and `api*-desktop.musixmatch.com` belongs after `traffic.libsyn.com`.

I had not seen it, now it's done.

**Pull request merged**
